import {test} from 'node:test';
import assert from 'node:assert/strict';
import {API_ROOT,TrainingAPI,consumeTokenFragment} from '../src/api';
test('fragment token removed immediately, other URL state retained, no storage needed',()=>{
 let address='';const token=consumeTokenFragment({hash:'#token=secret-token&view=review',pathname:'/training',search:'?local=1'},{state:null,replaceState:(_data,_unused,url)=>{address=url;}});assert.equal(token,'secret-token');assert.equal(address,'/training?local=1#view=review');assert.ok(!address.includes('secret-token'));
});
test('default fetch bound correctly; only explicit API actions send consent or markers',async()=>{
 const original=globalThis.fetch,calls:{url:string;method:string;body:any;authorization:string|null}[]=[];
 try{globalThis.fetch=async function(this:unknown,url,init){assert.equal(this,globalThis);const headers=new Headers(init?.headers);calls.push({url:String(url),method:init?.method??'GET',body:init?.body?JSON.parse(String(init.body)):null,authorization:headers.get('Authorization')});assert.equal(init?.credentials,'omit');assert.equal(init?.redirect,'error');return new Response(JSON.stringify(String(url).endsWith('/session')?{session:'ephemeral-session',status:{connected:false}}:{connected:false}),{status:200,headers:{'Content-Type':'application/json'}});};
 const api=new TrainingAPI();assert.equal(calls.length,0);await api.authenticate('startup-token-abcdefghijkl');assert.equal(calls.length,1);assert.deepEqual(calls[0].body,{});await api.connect('synthetic','synthetic rehearsal');await api.startRecord({participant_id:'fixture',refit_id:'fit1',role:'train',consent_statement:'Synthetic fixture only',seconds:20,metadata_confirmed:false});await api.marker({event:'down',id:'same-id',class_name:'double',client_ms:500});assert.equal(calls[1].url,API_ROOT+'/connect');assert.equal(calls[1].body.consent,true);assert.equal(calls[2].body.consent,true);assert.equal(calls[2].body.role,'train');assert.equal(calls[2].body.metadata_confirmed,false);assert.equal(calls[3].body.client_ms,500);assert.ok(!('device_s'in calls[3].body));assert.equal(calls[3].authorization,'Bearer ephemeral-session');api.close();await assert.rejects(()=>api.status(),/Connect the local/);
 }finally{globalThis.fetch=original;}
});
test('API errors retained; oversized body rejected before request; exact delete sent',async()=>{
 const calls:string[]=[];const bodies:any[]=[];const api=new TrainingAPI(async(url,init)=>{calls.push(String(url));bodies.push(init?.body?JSON.parse(String(init.body)):null);if(String(url).endsWith('/session'))return new Response(JSON.stringify({session:'memory-token',status:{}}));if(String(url).endsWith('/delete'))return new Response(JSON.stringify({}));return new Response(JSON.stringify({error:'no_eligible_real_sessions'}),{status:400});});await api.authenticate('startup-token-abcdefghijkl');await assert.rejects(()=>api.train(),/no_eligible_real_sessions/);await assert.rejects(()=>api.startRecord({participant_id:'p',refit_id:'f',role:'train',consent_statement:'x'.repeat(17000),seconds:20,metadata_confirmed:false}),/exceeds/);assert.equal(calls.length,2);await api.deleteSession('session-exact','session-exact');assert.deepEqual(bodies.at(-1),{session_id:'session-exact',confirmed_session_id:'session-exact'});
});
