import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {DEFAULT_SETTINGS,type Marker,type MusicSettings} from './model';
import {SCENE_EVENTS} from '../../../../packages/audio/keyboard-scenes';
import './style.css';

const API='/api/scenescore';
const steps=['Upload video','Split frames','Detect events','Compose & shape','Final cut'];
type Job={id:string;name:string;stage:string;error?:string;duration?:number;revision?:string;frames?:{file:string;at:number}[];analysis?:{summary:string;objects:{id:string;description:string}[];limitations:string[];markers:Marker[]};result?:any;api?:any};
async function request(url:string,options:RequestInit={}){const response=await fetch(url,{...options,headers:{'X-SceneScore':'1',...options.headers}});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function App(){
 const [job,setJob]=useState<Job|null>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[health,setHealth]=useState<{api_configured:boolean}|null>(null);
 const [markers,setMarkers]=useState<Marker[]>([]),[settings,setSettings]=useState<MusicSettings>(DEFAULT_SETTINGS),[dirty,setDirty]=useState(false),[time,setTime]=useState(0),[original,setOriginal]=useState(false),[drag,setDrag]=useState(false);
 const [recent,setRecent]=useState<{id:string;name:string;ready:boolean}[]>([]);
 const input=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),revision=useRef('');
 const duration=job?.duration??0,asset=(file:string)=>`${API}/${job!.id}/asset/${file}`;
 const complete=Boolean(job?.result&&job.revision),processing=Boolean(job&& !['Ready','Failed'].includes(job.stage));
 useEffect(()=>{request(`${API}/health`).then(setHealth).catch(()=>setError('Start start-scenescore.cmd, then open http://127.0.0.1:5188/scenescore.html.'));
  const id=new URLSearchParams(location.search).get('session')||localStorage.getItem('scenescore-session');if(id)request(`${API}/${id}`).then(accept).catch(()=>localStorage.removeItem('scenescore-session'));
 },[]);
 useEffect(()=>{request(`${API}/sessions`).then(setRecent).catch(()=>{});},[job?.stage]);
 function accept(next:Job){setJob(next);if(next.error)setError(next.error);if(next.result&&next.revision!==revision.current){revision.current=next.revision!;setMarkers(next.result.markers);setSettings(next.result.settings);setDirty(false);setTime(0);setOriginal(false);}else if(!next.result&&next.analysis)setMarkers(next.analysis.markers);}
 useEffect(()=>{if(!job||!processing)return;let cancelled=false;const timer=setInterval(()=>{request(`${API}/${job.id}`).then(next=>{if(!cancelled)accept(next);}).catch(e=>{if(!cancelled)setError(`Status unavailable: ${e.message}. Retrying…`);});},1000);return()=>{cancelled=true;clearInterval(timer);};},[job?.id,processing]);
 function choose(value:File|undefined){if(!value)return;if(value.size>128*1024*1024){setError('Choose a video under 128 MB.');return;}setFile(value);setError('');}
 async function upload(example?:'A'|'B'){
  if(!example&&!file)return;setBusy(true);setError('');video.current?.pause();
  try{const next=await request(`${API}/${example?'example':'upload'}`,{method:'POST',headers:example?{'Content-Type':'application/json'}:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(file!.name)},body:example?JSON.stringify({name:example}):file});revision.current='';setMarkers([]);setDirty(false);setOriginal(false);setTime(0);accept(next);localStorage.setItem('scenescore-session',next.id);}
  catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}
 }
 function edit(next:Marker[]){video.current?.pause();setMarkers(next);setDirty(true);}
 function changeSettings(next:MusicSettings){video.current?.pause();setSettings(next);setDirty(true);}
 async function rebuild(){if(!job)return;setBusy(true);setError('');video.current?.pause();try{accept(await request(`${API}/${job.id}/render`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({markers,settings})}));}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 function seek(at:number){if(video.current){video.current.currentTime=Math.max(0,Math.min(duration,at));setTime(at);}}
 function add(){edit([...markers,{id:Math.max(0,...markers.map(m=>m.id))+1,kind:3,at:Math.min(time,Math.max(0,duration-.001)),enabled:true,objects:[],evidence:'Manually placed event',start_s:Math.min(time,Math.max(0,duration-.001)),end_s:Math.min(time,Math.max(0,duration-.001)),confidence:'manual'}]);}
 const locked=busy||processing;
 const stageIndex=!job?0:job.stage==='Ready'?4:/Building/.test(job.stage)?4:/Compos|Applying/.test(job.stage)?3:/Analyzing/.test(job.stage)?2:1;
 return <main>
  <header><a className="brand" href="/scenescore.html"><span className="brand-icon">≋</span>SceneScore<span className="lab">MOTION STUDIO</span></a><span className="local"><i/> {health?.api_configured?'API key configured':'Manual mode available'}</span></header>
  <section className="intro"><div><p className="eyebrow">EVERY LITTLE MOVEMENT HAS A MELODY</p><h1>Make motion<br/><em>sound like something.</em></h1><p className="description">A video becomes frames. Frames become moments.<br/>An original score brings them together.</p></div><div className="intro-note"><span>01 — 05</span><svg viewBox="0 0 220 70" aria-hidden="true"><path d="M0 35 H25 L34 15 L45 55 L58 5 L72 65 L83 23 L95 46 L108 35 H126 L137 12 L147 58 L160 24 L174 43 L185 35 H220"/></svg><small>YOUR SCENE. YOUR SOUNDTRACK.</small></div></section>
  <nav className="steps" aria-label="Creation progress">{steps.map((step,i)=><div key={step} className={i===stageIndex?'current':i<stageIndex?'done':''}><span>{i<stageIndex?'✓':`0${i+1}`}</span>{step}</div>)}</nav>
  <section className="workspace">
   <aside className="upload-panel"><p className="eyebrow">01 / THE STARTING POINT</p><h2>Bring a little motion.</h2><p>Clips under 30 seconds.<br/>MP4, MOV or WebM · up to 128 MB.</p>
    <button className={`dropzone ${drag?'drag':''}`} disabled={locked} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!locked)choose(e.dataTransfer.files[0]);}}><span className="upload-symbol">↥</span><strong>{file?.name??'Drop your video here'}</strong><span>{file?`${(file.size/1024/1024).toFixed(1)} MB · click to change`:'or click to browse'}</span></button>
    <input ref={input} type="file" accept="video/*,.mov" aria-label="Choose video" hidden disabled={locked} onChange={e=>choose(e.target.files?.[0])}/>
    <button className="primary wide" disabled={locked||!file||!health} onClick={()=>void upload()}>{busy?'Uploading…':'Create soundtrack'} <span>↗</span></button>
    <p className="privacy">Creating sends sampled frames to OpenAI for analysis. Your API key stays on this computer. Original audio is replaced.</p>
    <div className="examples"><span>TRY OUR TEST CLIPS</span><div><button disabled={locked||!health} onClick={()=>void upload('A')}>Video A <span>↗</span></button><button disabled={locked||!health} onClick={()=>void upload('B')}>B · first 29s <span>↗</span></button></div></div>
    {recent.some(r=>r.ready)&&<label className="saved">REOPEN A SAVED DRAFT<select aria-label="Reopen a saved draft" value={job?.id??''} disabled={locked} onChange={e=>{if(e.target.value){setError('');setDirty(false);revision.current='';void request(`${API}/${e.target.value}`).then(next=>{accept(next);localStorage.setItem('scenescore-session',next.id);}).catch(e=>setError(e.message));}}}><option value="">Choose a result · no API call</option>{recent.filter(r=>r.ready).map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(0,6)}</option>)}</select></label>}
    <div className="spec"><div><strong>5 fps</strong><span>analysis fidelity</span></div><div><strong>0.2 s</strong><span>between samples</span></div></div>
   </aside>
   <section className="preview-panel"><div className="panel-heading"><span>{complete?'YOUR FINAL CUT':'THE PREVIEW'}</span><span className="pill">{dirty?'UNRENDERED EDITS':'DRAFT AUDITION'}</span></div>
    <div className="screen">{job?.duration?<video key={`${job.id}-${original?'source':job.revision??'preview'}`} ref={video} src={asset(!original&&job.revision?`${job.revision}/final.mp4`:'preview.mp4')} controls playsInline preload="metadata" onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onError={()=>setError('Video playback failed. Try downloading the MP4 or rebuilding the result.')} aria-label="SceneScore video playback"/>:<div className="empty-screen"><div className="frame-art"><span>♪</span><div className="ball"/><div className="floor"/></div><h3>A scene waiting for its score.</h3><p>Your finished video will play here.</p></div>}
     {processing&&<div className="processing"><span className="spinner"/><strong>{job!.stage}</strong><span>Keep this page open. You can review every event next.</span><button onClick={()=>void request(`${API}/${job!.id}/cancel`,{method:'POST'}).catch(e=>setError(e.message))}>Cancel processing</button></div>}
    </div>
    <div className="preview-caption"><div><strong>{job?.name??'From silent clip to original soundtrack'}</strong><span>{duration?`${duration.toFixed(2)} seconds · ${job?.frames?.length??0} analysis frames`:'Piano + fingerstyle guitar · original swing'}</span></div>{complete&&<button disabled={locked} onClick={()=>{video.current?.pause();setOriginal(!original);setTime(0);}}>{original?'Hear soundtrack':'View silent source'}</button>}</div>
    <div className="result-note">{dirty?'The player shows the last rendered version. Rebuild to hear your edits.':job?.analysis?.summary??'We look for approaches, near misses, contacts, releases and rebounds — then shape the music around them.'}</div>
   </section>
  </section>
  {error&&<div className="error" role="alert">{error}{job?.stage==='Failed'&&job.duration&&!job.analysis&&<button disabled={locked} onClick={()=>{setError('');void request(`${API}/${job.id}/recover`,{method:'POST'}).then(accept).catch(e=>setError(e.message));}}>Recover saved API response</button>}{job?.stage==='Failed'&&job.duration&&!job.analysis&&<button disabled={locked} onClick={()=>{setError('');void request(`${API}/${job.id}/manual`,{method:'POST'}).then(accept).catch(e=>setError(e.message));}}>Continue with manual events</button>}</div>}
  <div className="status" role="status" aria-live="polite">{processing?job?.stage:complete?'Your draft is ready. Play it, edit its moments, and make it yours.':job?.stage==='Failed'?'Processing stopped. Your completed analysis, if available, is still editable.':'Choose a video to begin.'}</div>
  {job?.analysis&&<section className="editor"><div className="section-heading"><div><p className="eyebrow">THE MOMENTS THAT MAKE THE MUSIC</p><h2>Fine-tune the story.</h2></div><div><span className="event-count">{markers.filter(m=>m.enabled).length} active / {markers.length} events</span><button disabled={locked||markers.length>=64} onClick={add}>+ Add at playhead</button></div></div>
   <div className="timeline" aria-label="Event timeline">{[0,.25,.5,.75,1].map(t=><div key={t} className="gridline" style={{left:`${t*100}%`}}><span>{(t*duration).toFixed(1)}s</span></div>)}{markers.map(m=><button key={m.id} className={`dot k${m.kind} ${m.enabled?'':'disabled'}`} style={{left:`${m.at/duration*100}%`,top:`${38+m.kind*19}px`}} aria-label={`Seek ${SCENE_EVENTS[m.kind].name} at ${m.at.toFixed(2)} seconds`} title={`${SCENE_EVENTS[m.kind].name} · ${m.at.toFixed(2)}s`} onClick={()=>seek(m.at)}>{m.kind+1}</button>)}<div className="playhead" style={{left:`${Math.min(100,time/duration*100)}%`}}/></div>
   <div className="legend">{SCENE_EVENTS.map((s,i)=><span key={s.name}><i className={`k${i}`}/>{s.name}</span>)}</div>
   <div className="editor-layout"><div className="event-list">{!markers.length&&<p className="no-events">No supported events were detected. The original music still plays; add a marker to shape a moment manually.</p>}{markers.map(m=><article key={m.id} className={`event-row ${m.enabled?'':'off'}`}><div className="event-top"><label className="enable"><input type="checkbox" checked={m.enabled} disabled={locked} aria-label={`Enable event ${m.id}`} onChange={e=>edit(markers.map(x=>x.id===m.id?{...x,enabled:e.target.checked}:x))}/><span className={`number k${m.kind}`}>{m.kind+1}</span></label><select aria-label={`Event ${m.id} type`} value={m.kind} disabled={locked} onChange={e=>edit(markers.map(x=>x.id===m.id?{...x,kind:Number(e.target.value),confidence:'manual'}:x))}>{SCENE_EVENTS.map((s,i)=><option key={s.name} value={i}>{s.name}</option>)}</select><label className="seconds"><input type="number" aria-label={`Event ${m.id} time`} min="0" max={duration-.001} step="0.2" value={m.at} disabled={locked} onChange={e=>{if(e.target.value==='')return;const at=Number(e.target.value);if(Number.isFinite(at)&&at>=0&&at<duration)edit(markers.map(x=>x.id===m.id?{...x,at,confidence:'manual'}:x));}}/> s</label><button className="delete" disabled={locked} aria-label={`Delete event ${m.id}`} onClick={()=>edit(markers.filter(x=>x.id!==m.id))}>×</button></div><p>{SCENE_EVENTS[m.kind].effect}</p><details><summary>{m.confidence==='manual'?'Manual edit':m.confidence==='uncertain'?'Uncertain proposal':'API proposal'} · {m.objects.join(' + ')||'scene'} · evidence</summary><p>{m.evidence}</p><small>Source interval: {m.start_s.toFixed(1)}–{m.end_s.toFixed(1)}s</small></details></article>)}</div>
    <aside className="music-panel"><p className="eyebrow">THE MUSICAL PALETTE</p><h3>Little Signals</h3><p>An original swing phrase, arranged locally to fit your clip. The piano and guitar keep their voices throughout.</p><label>Guitar ornament<select disabled={locked} value={settings.ornament} onChange={e=>changeSettings({...settings,ornament:e.target.value as MusicSettings['ornament']})}>{['plain','grace','turn','trill'].map(o=><option key={o}>{o}</option>)}</select></label><label>Touch<select disabled={locked} value={settings.touch} onChange={e=>changeSettings({...settings,touch:e.target.value as MusicSettings['touch']})}>{['legato','detached','staccato'].map(o=><option key={o}>{o}</option>)}</select></label><label>Key shift<select disabled={locked} value={settings.transpose} onChange={e=>changeSettings({...settings,transpose:Number(e.target.value)})}>{[-12,-10,-8,-6,-4,-2,0,2,4,6,8,10,12].map(n=><option key={n} value={n}>{n>0?'+':''}{n} semitones</option>)}</select></label><label>Mix level · {settings.gainDb} dB<input type="range" disabled={locked} min="-24" max="-6" value={settings.gainDb} onChange={e=>changeSettings({...settings,gainDb:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={settings.effects} disabled={locked} onChange={e=>changeSettings({...settings,effects:e.target.checked})}/> Apply event effects</label><button className="primary wide" disabled={locked} onClick={()=>void rebuild()}>{locked?'Building…':'Rebuild soundtrack'} <span>↗</span></button><button className="reset" disabled={locked} onClick={()=>edit(job.analysis!.markers)}>Restore API proposals</button><small>No extra API call. Rebuild applies your current events and music settings.</small></aside>
   </div>
  </section>}
  {complete&&<section className="exports"><div><p className="eyebrow">TAKE IT WITH YOU</p><h2>Your scene. Now with a score.</h2><p>MP4, lossless audio, separate voices and an editable score.</p>{dirty&&<strong>Downloads contain the last rendered version.</strong>}</div><div className="download-links"><a className="primary" download="SceneScore-DRAFT.mp4" href={asset(`${job!.revision}/final.mp4`)}>↓ Final video</a><a download href={asset(`${job!.revision}/mix.wav`)}>↓ Music WAV</a><a download href={asset(`${job!.revision}/score.json`)}>↓ Editable score</a><a download href={asset(`${job!.revision}/piano.wav`)}>↓ Piano stem</a><a download href={asset(`${job!.revision}/guitar.wav`)}>↓ Guitar stem</a></div></section>}
  {job?.frames&&<details className="evidence"><summary>Frames, object identities & analysis details</summary><p>5 fps provides one sample every 0.2 seconds. Contact proposals can be ambiguous in 2D; uncertain events start disabled. These are draft musical choices, not verified physical events.</p>{job.analysis?.objects.map(o=><p key={o.id}><strong>{o.id}</strong> — {o.description}</p>)}{job.analysis?.limitations.map((l,i)=><p key={i}>{l}</p>)}<div className="filmstrip">{job.frames.map(f=><button key={f.file} onClick={()=>seek(f.at)}><img loading="lazy" src={asset(f.file)} alt={`Analysis frame at ${f.at.toFixed(1)} seconds`}/><span>{f.at.toFixed(1)}s</span></button>)}</div><p>{job.result?.score.mapping}</p>{['live_api','cached_gpt'].includes(job.api?.source_mode)?<p>{job.api.source_mode==='cached_gpt'?'Cached API response':'Live API'} · {job.api.returned_model} · {job.api.elapsed_ms===null?'latency not recorded':`${(job.api.elapsed_ms/1000).toFixed(1)}s`} · original audio not analyzed</p>:job.api&&<p>Manual plan · no successful API analysis</p>}{job.result&&<p>48 kHz stereo · peak {job.result.audio[0].peak.toFixed(3)} · {job.result.audio[0].clipped} clipped samples · approval: null</p>}</details>}
  <footer><span>SCENESCORE <b> / </b> FROM MOTION TO MUSIC</span><span>Original music · editable proposals · human audition pending</span></footer>
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
