'use strict';
const $=id=>document.getElementById(id);
let state={samples:[],events:[],status:'idle',mode:'synthetic',doubles:0}, busy=false, began=null, previousDoubles=0, toastTimer;
function notice(message){$('error').textContent=message;$('error').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('error').hidden=true,8000)}
async function post(path,data={}){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Muse-Test':'1'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error);return result}
function sourceUI(){const live=$('source').value==='real_device';$('hardware').hidden=!live;$('simulation').hidden=live;$('liveHint').hidden=!live;$('start').innerHTML=(live?'Connect headset':'Start simulation')+' <span>↗</span>';$('sourceHelp').textContent=live?'Bluetooth connects through the local Python app. Keep other Muse apps closed.':'Explore the full detector with generated signals. No headset connection is made.';$('modeBadge').textContent=live?'REAL HEADSET':'SIMULATION';$('disclaimer').textContent=live?'Experimental detection. Contact quality and blink intent are unverified.':'Simulation tests software behavior, not real-headset accuracy.'}
$('source').onchange=sourceUI;
$('threshold').oninput=()=>{$('thresholdValue').value=Number($('threshold').value).toFixed(1)};
$('start').onclick=async()=>{if(busy)return;busy=true;$('start').disabled=true;try{await post('start',{mode:$('source').value,threshold:Number($('threshold').value),name:$('name').value,unplugged:$('unplugged').checked});began=Date.now();previousDoubles=0}catch(error){notice(error.message)}finally{busy=false;await poll()}};
$('stop').onclick=async()=>{try{await post('stop');$('stop').disabled=true}catch(error){notice(error.message)}};
document.querySelectorAll('[data-count]').forEach(button=>button.onclick=async()=>{try{await post('inject',{count:Number(button.dataset.count)})}catch(error){notice(error.message)}});
function render(){const running=['connecting','calibrating','ready'].includes(state.status);$('start').disabled=running||busy;$('stop').disabled=!running;['source','threshold','name','unplugged'].forEach(id=>$(id).disabled=running);if(running&&$('source').value!==state.mode){$('source').value=state.mode;sourceUI()}$('status').textContent=state.status==='ready'?'Listening':state.status[0].toUpperCase()+state.status.slice(1);$('status').className='status '+state.status;
 const copy={idle:['Ready when you are.','Start a session to see the two forehead channels.'],connecting:['Connecting to your headset…','Keep the charged headset unplugged and close other Muse apps.'],calibrating:['Finding your baseline…',`Relax and sit still. ${Math.round(state.progress*100)}% complete.`],ready:['Listening for your double blink.',state.mode==='synthetic'?'Try a signal below. Singles and triples should be rejected.':'Blink twice comfortably. The detector waits briefly for the gesture to finish.'],stopped:['Session stopped.','Start again to recalibrate and begin a fresh test.'],error:['The session needs attention.',state.error||'Restart after checking your headset.']};const [title,detail]=copy[state.status]||copy.idle;$('instruction').textContent=title;$('detail').textContent=detail;$('calibration').value=state.progress;$('blinks').textContent=state.blinks||0;$('doubles').textContent=state.doubles||0;
 if(running&&began){const seconds=Math.floor((Date.now()-began)/1000);$('elapsed').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
 document.querySelectorAll('[data-count]').forEach(button=>button.disabled=state.status!=='ready'||state.mode!=='synthetic');if(state.doubles>previousDoubles){const metric=$('doubles').parentElement;metric.classList.remove('flash');void metric.offsetWidth;metric.classList.add('flash')}previousDoubles=state.doubles;
 const fragment=document.createDocumentFragment();[...state.events].reverse().forEach(event=>{const row=document.createElement('div');row.className='event-row'+(event.event==='double_blink'?' success':'');const when=document.createElement('time');when.textContent=new Date(event.received*1000).toLocaleTimeString([],{hour12:false});const label=document.createElement('span');label.textContent={ready:'Calibration complete',blink:'Blink candidate',double_blink:'Double blink detected',rejected_train:`${event.blink_count===1?'Single blink':event.blink_count===3?'Triple blink':'Ambiguous gesture'} · no command`}[event.event]||event.event;const mode=document.createElement('small');mode.textContent=event.source_mode==='synthetic'?'SIMULATED':'HEADSET';row.append(when,label,mode);fragment.append(row)});if(state.events.length)$('events').replaceChildren(fragment);else $('events').innerHTML='<div class="empty">Your session events will appear here.</div>';draw()}
function draw(){const canvas=$('signal'),rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=rect.height;ctx.strokeStyle='#edf1e9';ctx.lineWidth=1;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(0,i*h/4);ctx.lineTo(w,i*h/4);ctx.stroke()}for(let i=0;i<9;i++){ctx.beginPath();ctx.moveTo(i*w/8,0);ctx.lineTo(i*w/8,h);ctx.stroke()}const data=state.samples;if(!data.length)return;const end=data.at(-1)[0];['#329680','#98afc6'].forEach((color,index)=>{ctx.strokeStyle=color;ctx.lineWidth=index?1.4:1.8;ctx.beginPath();let first=true;data.forEach(row=>{const x=(row[0]-end+8)/8*w;if(x<0)return;const y=h/2-Math.max(-200,Math.min(200,row[index+1]))/400*h;if(first){ctx.moveTo(x,y);first=false}else ctx.lineTo(x,y)});ctx.stroke()})}
async function poll(){try{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw Error('Local server unavailable');state=await response.json();render()}catch(error){$('status').textContent='Offline';$('instruction').textContent='Start the local test app.';$('detail').textContent='Run python tools/muse_test_app.py, then refresh this page.';$('start').disabled=true;$('stop').disabled=true;document.querySelectorAll('[data-count]').forEach(b=>b.disabled=true)}}
window.addEventListener('resize',draw);sourceUI();poll();setInterval(poll,150);
