/** Bounded browser smoke test. Supply an already installed playwright-core module. */
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.SCENESCORE_PLAYWRIGHT_MODULE).href);
const root=process.cwd(),out=path.join(root,'output/playwright/catalog');mkdirSync(out,{recursive:true});
const checks=[],errors=[];let browser;
const record=(name,evidence)=>{checks.push({name,status:'passed',evidence});console.log(name+': passed');};
const deadline=setTimeout(()=>{console.error('Browser check deadline exceeded');void browser?.close();},150000);
try{
 browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.SCENESCORE_CATALOG_URL??'http://127.0.0.1:8794');
 await page.getByRole('heading',{name:'Video library',exact:true}).waitFor();
 await page.getByRole('button',{name:'Watch Projectile & tower',exact:true}).waitFor();
 const total=await page.locator('.video-item').count();assert.ok(total>=43);
 const live=await page.evaluate(async()=> (await(await fetch('/library/catalog.json')).json()).coverage.live_scores);
 await page.getByRole('button',{name:`Live soundtracks ${live}`,exact:true}).click();assert.equal(await page.locator('.video-item').count(),live);
 await page.waitForFunction(()=>[...document.querySelectorAll('.video-preview video')].every(v=>v.readyState>=2));
 await page.screenshot({path:path.join(out,'library-desktop.png'),fullPage:true,animations:'disabled'});record('catalog groups soundtrack variants and includes video accompaniment',live);
 await page.getByRole('searchbox',{name:'Search videos'}).fill('A near miss');assert.equal(await page.locator('.video-item').count(),1);
 await page.getByRole('searchbox',{name:'Search videos'}).fill('unfindable-title');await page.getByText('No matching animations').waitFor();
 await page.getByRole('button',{name:'Clear search'}).click();record('search and empty state',true);
 await page.getByRole('button',{name:'Watch Projectile & tower',exact:true}).click();
 const play=page.getByRole('button',{name:'▶ Watch & listen',exact:true});await play.waitFor();await page.waitForFunction(()=>!document.querySelector('.primary-play')?.disabled);
 await play.click();await page.getByRole('button',{name:'Pause',exact:true}).waitFor();
 await page.waitForFunction(()=>window.__studio.snapshot().time>1);
 const played=await page.evaluate(()=>{const s=window.__studio.snapshot();return {time:s.time,playing:s.playing,scheduled:s.scheduled.length,approval:s.approval,bundle:s.bundle_id};});
 assert.ok(played.playing&&played.scheduled>0&&played.approval===null);record('unapproved watch and live audio scheduling',played);
 await page.getByRole('checkbox',{name:'Music',exact:true}).uncheck();
 await page.getByRole('checkbox',{name:'Sound effects',exact:true}).uncheck();
 await page.getByRole('checkbox',{name:'Music',exact:true}).check();
 await page.getByRole('checkbox',{name:'Sound effects',exact:true}).check();
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 const downloads=[];page.on('download',d=>downloads.push(d));
 await page.getByRole('button',{name:'Download video + sidecar',exact:true}).click();
 await page.waitForTimeout(600);assert.equal(downloads.length,2);record('download original video and exact prepared sidecar',downloads.map(d=>d.suggestedFilename()));
 const audio=await page.evaluate(()=>window.__studio.offline());assert.ok(audio.rms>0&&audio.clipped===0&&audio.duration_s===30);record('actual offline stereo audio',audio);
 await page.screenshot({path:path.join(out,'player-desktop.png'),fullPage:true});
 const tracks=page.getByRole('combobox',{name:'Soundtrack version'}),options=await tracks.locator('option').evaluateAll(o=>o.map(x=>x.value));
 await tracks.selectOption(options[1]);await page.waitForFunction(()=>!document.querySelector('.primary-play')?.disabled);
 assert.equal((await page.evaluate(()=>window.__studio.snapshot())).approval,null);record('change soundtrack resets playback and approval',options[1]);
 await page.getByRole('button',{name:'← Video library',exact:true}).click();
 await page.getByRole('button',{name:'＋ Add video bundle'}).click();
 await page.getByLabel('Blender video · MP4').setInputFiles(path.join(root,'apps/web/public/riff-studio/near-miss.mp4'));
 await page.getByLabel('Prepared sidecar · JSON').setInputFiles(path.join(root,'apps/web/public/riff-studio/contact-brush_swing_light_v1-guitar-piano-v2.json'));
 await page.getByRole('button',{name:'Add to library',exact:true}).click();await page.getByRole('alert').filter({hasText:'Video hash mismatch'}).waitFor();record('wrong uploaded video rejected',true);
 await page.getByLabel('Blender video · MP4').setInputFiles(path.join(root,'apps/web/public/riff-studio/contact.mp4'));
 await page.getByRole('button',{name:'Add to library',exact:true}).click();await page.getByRole('status').filter({hasText:'added to this browser'}).waitFor();
 await page.reload();await page.getByRole('button',{name:'On this device 1',exact:true}).click();assert.equal(await page.locator('.video-item').count(),1);record('import survives browser reload',true);
 await page.getByRole('button',{name:'Watch Projectile & tower',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.primary-play')?.disabled);
 await context.setOffline(true);await page.getByRole('button',{name:'▶ Watch & listen',exact:true}).click();await page.waitForFunction(()=>window.__studio.snapshot().time>1);
 const imported=await page.evaluate(()=>window.__studio.snapshot());assert.equal(imported.approval,null);assert.ok(imported.playing);record('imported bundle plays offline',true);
 await page.getByRole('button',{name:'← Video library',exact:true}).click();await context.setOffline(false);
 await page.getByRole('button',{name:'Remove browser copy of Projectile & tower'}).click();await page.getByRole('status').filter({hasText:'Removed the browser copy'}).waitFor();record('remove imported browser copy',true);
 await page.getByRole('button',{name:`All videos ${total}`,exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'library-mobile.png'),fullPage:true,animations:'disabled'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));record('mobile library has no horizontal overflow',true);
 await page.getByRole('button',{name:'Watch 05 bouncing staircase',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.primary-play')?.disabled);
 await page.getByRole('button',{name:'▶ Watch & listen',exact:true}).click();await page.waitForFunction(()=>window.__studio.snapshot().complete,{},{timeout:20000});
 const short=await page.evaluate(()=>window.__studio.snapshot());assert.equal(short.time,8);record('second scene completes at its own duration',short.time);
 await page.screenshot({path:path.join(out,'player-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'← Video library',exact:true}).click();record('player teardown on catalog navigation',true);
 assert.deepEqual(errors,[]);record('browser page errors',errors);
}catch(error){checks.push({name:'browser smoke',status:'failed',error:String(error)});console.error(error);process.exitCode=1;}
finally{clearTimeout(deadline);await browser?.close();writeFileSync(path.join(out,'checks.json'),JSON.stringify({checks,errors,physical_output_measured:false,human_audition:'NOT_RUN',browser_closed:true},null,2)+'\n');}
