import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Approval,ArrangementPlan} from '../../../packages/contracts/generated';
import {approve,Bundle,copy,hash,Mode,sha,stable,verifyApproval,verifyBundle,bound} from '../../../packages/audio/model';
import {EFFECT_MIX} from '../../../packages/audio/effect-mix';
import {Engine,measurements,pcmWav,renderPerformedOffline} from '../../../packages/audio/engine';
import {stemsFor} from '../../../packages/audio/mix';
import type {RoleSupplement} from '../../../packages/audio/blender-inputs';
import {Timeline,videoCorrection} from '../../../packages/audio/transport';
import {createSimulation,createFromGesture,dispatchControl,latencyIntervals,prepareMotionReader,type ControlEnvelope,type MusicControlContext} from '../../../packages/audio/control';
import {createManualKeyChange,manualChoices} from '../../../packages/audio/manual-control';
import {MusePanel} from './muse/MusePanel';
import {Library} from './library/Library';
import {inspectImport,soundtrackName,type Entry,type ImportedVideo} from './library/catalog';
import {defaultPlaybackGain} from './library/playback-gain';
import './style.css';
const musicStudio=new URLSearchParams(window.location.search).get('music')==='1';
const reviewStudio=new URLSearchParams(window.location.search).get('review')==='1';
const studioRoot=reviewStudio?'/blender-review/':musicStudio?'/music-vertical/':'/studio/';
const keys=['C','D♭','D','E♭','E','F','G♭','G','A♭','A','B♭','B'];
function download(value:BlobPart,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function App({initialEntries,imported,onBack}:{initialEntries?:Entry[];imported?:ImportedVideo;onBack?:()=>void}){
 const [catalog,setCatalog]=useState<Entry[]>([]),[selection,setSelection]=useState(''),[bundle,setBundle]=useState<Bundle|null>(null),[plan,setPlan]=useState<ArrangementPlan|null>(null),[videoURL,setVideoURL]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('Loading local scene…'),[busy,setBusy]=useState(false),[mode,setMode]=useState<Mode>('KEYBOARD'),[reviewer,setReviewer]=useState(''),[approved,setApproved]=useState<{payload:string;approval:Approval}|null>(null),[tick,setTick]=useState(0),[gain,setGain]=useState(-18),[mute,setMute]=useState(false),[soundtrack,setSoundtrack]=useState(true),[foley,setFoley]=useState(true),[armed,setArmed]=useState(false),[drifts,setDrifts]=useState<number[]>([]);
 const [draftConducting,setDraftConducting]=useState(false);
 const [mediaReady,setMediaReady]=useState(false);
 const [headsetDetected,setHeadsetDetected]=useState(false);
 const loadedProfile=useRef(false);
 const sourceBytes=useRef<ArrayBuffer|null>(null);
 const frameTiming=useRef<Record<string,number>[]>([]);
 const controlTraces=useRef<ControlEnvelope[]>([]);
 const motionReader=useRef<(at:number)=>-2|0|2>(()=>0);
 const engine=useRef<Engine|null>(null),video=useRef<HTMLVideoElement>(null),videoObject=useRef(''),loadGeneration=useRef(0),lastCorrection=useRef(-10),replayFired=useRef(false);
 const time=engine.current?.now()??0,playing=engine.current?.timeline.playing??false,duration=bundle?.scene.duration_s??0;
 useEffect(()=>{let active=true;const ready=(entries:Entry[])=>{if(active){setCatalog(entries);setSelection(entries[0]?.id??'');}};if(initialEntries)ready(initialEntries);else fetch(studioRoot+'catalog.json').then(r=>{if(!r.ok)throw Error('Run the local scene preparation command before opening the studio.');return r.json();}).then(d=>ready(d.entries)).catch(e=>{if(active)setError(String(e));});return()=>{active=false;loadGeneration.current++;video.current?.pause();void engine.current?.close();if(videoObject.current)URL.revokeObjectURL(videoObject.current);};},[]);
 useEffect(()=>{if(!catalog.length)return;void load(selection);},[catalog,selection]);
 async function load(id:string){const generation=++loadGeneration.current;setBusy(true);setMediaReady(false);setError('');setMessage('Loading video and soundtrack…');setApproved(null);setDraftConducting(false);setArmed(false);video.current?.pause();setVideoURL('');setBundle(null);setPlan(null);controlTraces.current=[];frameTiming.current=[];const old=engine.current;engine.current=null;await old?.close();try{
  const entry=catalog.find(e=>e.id===id);if(!entry)throw Error('Unknown local scene');let raw:ArrayBuffer,media:ArrayBuffer;
  if(imported){await inspectImport(new Blob([imported.raw]),imported.media);raw=new TextEncoder().encode(imported.raw).buffer;media=await imported.media.arrayBuffer();}
  else{const response=await fetch(initialEntries?entry.url:studioRoot+entry.url);if(!response.ok)throw Error('Scene could not be loaded');raw=await response.arrayBuffer();if(await sha(raw)!==entry.sha256)throw Error('Scene bundle hash mismatch');const source=JSON.parse(new TextDecoder().decode(raw)) as Bundle;const responseVideo=await fetch(new URL(source.video,response.url));if(!responseVideo.ok)throw Error('Matched video is unavailable');media=await responseVideo.arrayBuffer();}
  if(await sha(raw)!==entry.sha256)throw Error('Scene bundle hash mismatch');const b=JSON.parse(new TextDecoder().decode(raw)) as Bundle,p=await verifyBundle(b,media);if(generation!==loadGeneration.current)return;sourceBytes.current=raw;if(videoObject.current)URL.revokeObjectURL(videoObject.current);videoObject.current=URL.createObjectURL(new Blob([media],{type:'video/mp4'}));setVideoURL(videoObject.current);setBundle(b);if(!loadedProfile.current){setGain(defaultPlaybackGain(b));loadedProfile.current=true;}setPlan(p);setDrifts([]);setMessage('Ready · press Watch & listen');replayFired.current=false;
 }catch(e){if(generation===loadGeneration.current){setError(String(e));setBundle(null);setPlan(null);}}finally{if(generation===loadGeneration.current)setBusy(false);}}
 function edited(next:ArrangementPlan){if(playing){setError('Pause before editing the arrangement.');return;}setPlan(next);setApproved(null);setArmed(false);void engine.current?.close();engine.current=null;setMessage('Arrangement changed · approval cleared');setTick(n=>n+1);}
 async function newEngine(preview:boolean,override:ArrangementPlan|null=plan){if(!bundle||!plan)throw Error('Load a scene first');if(!preview&&!approved)throw Error('Approve this exact arrangement before performance');const verified=preview?override!:await verifyApproval(approved!.payload,approved!.approval,bundle);const b=copy(bundle);b.events=b.events.map(e=>({...e,midi_pitch:e.midi_pitch===null?null:bound(e.midi_pitch,verified.register_min,verified.register_max)}));motionReader.current=prepareMotionReader(b,verified);const timeline=new Timeline(b,verified,preview?await hash(verified):approved!.approval.approved_payload_sha256);if(engine.current)await engine.current.close();const next=new Engine(timeline);next.gainDb=gain;next.mute=mute;next.lanes={soundtrack,foley};next.onTick=()=>setTick(n=>n+1);next.onSuspend=()=>{video.current?.pause();setMessage('Audio suspended · press Play to resume');};engine.current=next;return next;}
 async function start(preview=false){
  const load=loadGeneration.current;setBusy(true);setError('');let e=engine.current;
  try{if(!e)e=await newEngine(preview);if(!preview)await verifyApproval(approved!.payload,approved!.approval,bundle!);await e.unlock();
   if(load!==loadGeneration.current||engine.current!==e){await e.close();return;}
   if(bundle?.playback_window){await e.play();const generation=e.timeline.generation;await new Promise(resolve=>setTimeout(resolve,Math.max(0,(e!.anchorAudio-e!.context!.currentTime)*1000)));if(load!==loadGeneration.current||!e.timeline.playing||engine.current!==e||e.timeline.generation!==generation)return;if(video.current){video.current.playbackRate=1;video.current.currentTime=e.now();await video.current.play();}}
   else{if(video.current){if(Math.abs(video.current.currentTime-e.timeline.position)>.03)video.current.currentTime=e.timeline.position;await video.current.play();}if(load!==loadGeneration.current||engine.current!==e)return;await e.play();}
   if(load!==loadGeneration.current||engine.current!==e){await e.close();return;}
   setMessage(preview?'Draft soundtrack · audition pending':mode==='SYNTHETIC_TEST'?'Synthetic test · test approval only':'Approved plan playing locally');
  }catch(error){if(load===loadGeneration.current){e?.pause();video.current?.pause();setError(String(error));}}
  finally{if(load===loadGeneration.current)setBusy(false);}
 }
 function pause(){engine.current?.pause();video.current?.pause();setMessage('Paused · pending controls cleared');}
 function downloadSource(){if(!bundle||!sourceBytes.current||!videoURL)return;download(sourceBytes.current,'scenescore-sidecar.json');const a=document.createElement('a');a.href=videoURL;a.download=bundle.video.split('/').at(-1)||'animation.mp4';a.click();setMessage('Original video + prepared sidecar downloaded. Add both files to another browser’s library.');}
 async function accept(){if(!plan)return;try{pause();const a=await approve(plan,reviewer,mode==='SYNTHETIC_TEST');setApproved(a);await engine.current?.close();engine.current=null;setMessage(mode==='SYNTHETIC_TEST'?'Test approval recorded · no human audition claimed':'Exact plan approved · listening status still pending');}catch(e){setError(String(e));}}
 function getPlaybackContext(requestAudioS?:number):MusicControlContext|null{
  const e=engine.current;if(!e?.context||!e.timeline.playing)return null;
  const audio_s=requestAudioS??e.context.currentTime,scene_s=e.anchorScene+audio_s-e.anchorAudio;
  return {audio_s,audio_epoch:e.timeline.epoch,approved_plan_hash:e.timeline.planHash,scene_policy_id:e.timeline.plan.motion_policy.id,signed_semitones:motionReader.current(scene_s),lanes:{master_gain_db:gain,articulation:'score',expression_preset:'neutral'},expires_after_s:6};
 }
 function getMusicContext(requestAudioS?:number):MusicControlContext|null{
  return armed&&(approved||draftConducting)?getPlaybackContext(requestAudioS):null;
 }
 function receiveControl(envelope:ControlEnvelope,manual=false){
  const e=engine.current;if(!e||!(manual&&!headsetDetected?getPlaybackContext():getMusicContext()))return {status:'suppressed',reason:'transport_not_armed'};
  try{const result=dispatchControl(e,envelope);controlTraces.current=[...controlTraces.current.slice(-199),envelope];
   setMode(({keyboard:'KEYBOARD',synthetic:'SYNTHETIC_TEST',replay:'REAL_REPLAY',real_device:'LIVE_MUSE'} as const)[envelope.action.provenance.source_mode as 'keyboard'|'synthetic'|'replay'|'real_device']??'SYNTHETIC_TEST');
   setMessage(result.status==='queued'?`${manual?'Manual key change queued':'Key change queued'} · ${result.signed_semitones!>0?'+':''}${result.signed_semitones} semitones · tonic arrives at ${result.arrival_scene_s!.toFixed(2)}s`:result.reason??result.status);return result;
  }catch(error){setError(String(error));return {status:'suppressed',reason:String(error)};}
 }
 function changeKey(){
  const e=engine.current,context=getPlaybackContext();if(headsetDetected||busy||!e||!context)return;
  const seed=crypto.getRandomValues(new Uint32Array(1))[0];
  const envelope=createManualKeyChange(e.timeline,context.audio_s,e.now(),context.lanes,seed);
  if(!envelope){setMessage('No prepared key change fits here. Wait for the current transition or return to the start.');return;}
  receiveControl(envelope,true);
 }
 function conduct(){const context=getMusicContext();if(!context){setMessage('Start the draft demo or approve, play and arm conducting');return;}receiveControl(createSimulation(context,'keyboard'));}
 async function startDemo(){setBusy(true);setError('');try{if(!bundle||!plan)throw Error('Load a scene first');
  const moving=bundle.states.find(s=>(!(bundle.role_supplement as RoleSupplement|null)?.scored_object_ids||(bundle.role_supplement as RoleSupplement).scored_object_ids.includes(s.object_id))&&s.velocity_m_s&&Math.abs(s.velocity_m_s[2])>plan.motion_policy.deadband_m_s);
  const next={...copy(plan),motion_policy:{...plan.motion_policy,focus_object_id:bundle.music_vertical?plan.motion_policy.focus_object_id:moving?.object_id??plan.motion_policy.focus_object_id}};
  setPlan(next);setApproved(null);setDraftConducting(true);setArmed(true);setMode('KEYBOARD');controlTraces.current=[];replayFired.current=true;
  const cue=bundle.states.find(s=>s.object_id===next.motion_policy.focus_object_id&&s.scene_time_s<bundle.scene.duration_s-4&&directionAt(bundle,next,s.scene_time_s)!==0);
  const demoEngine=await newEngine(true,next);if(cue&&!bundle.music_vertical)demoEngine.seek(cue.scene_time_s);await start(true);setMessage(`DRAFT DEMO · starts at motion cue ${(bundle.music_vertical?0:cue?.scene_time_s??0).toFixed(2)}s · conducting enabled · approval pending`);
 }catch(error){setError(String(error));setDraftConducting(false);setArmed(false);}finally{setBusy(false);}}

 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if((event.target as HTMLElement).matches('input,select,textarea,button,summary')||busy||!mediaReady)return;if(event.code==='Space'){event.preventDefault();playing?pause():void start(!approved);}if(event.code==='KeyM'){event.preventDefault();conduct();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);});
 const fixtureTime=bundle?.playback_window?(bundle.fixture_markers?.find(m=>m.type==='release'||m.type==='contact')?.confirmation_time_s??bundle.interactions.find(e=>e.event_type==='contact_onset')?.onset_s):18;
 useEffect(()=>{if(mode==='SYNTHETIC_TEST'&&playing&&armed&&fixtureTime!==undefined&&time>=fixtureTime&&!replayFired.current){replayFired.current=true;const context=getMusicContext();if(context)receiveControl(createSimulation(context));}},[tick,mode,armed]);
 useEffect(()=>{const v=video.current;if(!v)return;let cancelled=false,handle=0;const callback=(_now:number,meta?:{mediaTime:number;expectedDisplayTime:number;presentedFrames:number})=>{if(cancelled)return;const e=engine.current;if(e?.timeline.playing){const callbackTime=performance.now(),contextTime=e.context?.currentTime??0;const expected=e.timeline.bundle.playback_window&&meta?Math.max(0,e.anchorScene+contextTime-e.anchorAudio+(meta.expectedDisplayTime-callbackTime)/1000):e.now();const drift=(meta?.mediaTime??v.currentTime)-expected;if(meta&&e.context&&e.timeline.bundle.playback_window)frameTiming.current=[...frameTiming.current.slice(-499),{media_time_s:meta.mediaTime,presentation_time_ms:meta.expectedDisplayTime,callback_time_ms:callbackTime,audio_context_s:contextTime,anchor_audio_s:e.anchorAudio,anchor_scene_s:e.anchorScene,expected_scene_s:expected,drift_s:drift,presented_frames:meta.presentedFrames,generation:e.timeline.generation}];setDrifts(prev=>[...prev.slice(-199),drift]);const correction=videoCorrection(drift,e.now()-lastCorrection.current);if(correction.seek){v.currentTime=e.now();lastCorrection.current=e.now();}else v.playbackRate=correction.rate;}if('requestVideoFrameCallback'in v)handle=v.requestVideoFrameCallback(callback);else handle=requestAnimationFrame(callback);};if('requestVideoFrameCallback'in v)handle=v.requestVideoFrameCallback(callback);else handle=requestAnimationFrame(callback);return()=>{cancelled=true;if('cancelVideoFrameCallback'in v)v.cancelVideoFrameCallback(handle);else cancelAnimationFrame(handle);};},[videoURL]);
 async function exportAudio(isDraft:boolean){
  if(!bundle||!plan)return;setError('');setBusy(true);
  try{
   const e=engine.current??await newEngine(true);
   if(!isDraft){if(!approved)throw Error('An approved performance is required');await verifyApproval(approved.payload,approved.approval,bundle);e.exportReady();}
   pause();const performed=e.timeline.performedEvents();const mix=isDraft?[{scene_s:0,gain_db:gain,muted:mute,lanes:{soundtrack,foley}}]:e.exportMix();
   const prefix=isDraft?'scenescore-DRAFT':'scenescore-performance';
   const files=[];
   for(const stem of ['mix',...stemsFor(performed)] as const){
    const buffer=await renderPerformedOffline(e.timeline,bundle.scene.duration_s,gain,{soundtrack,foley},48000,mix,stem==='mix'?undefined:stem),wav=pcmWav(buffer),filename=prefix+(stem==='mix'?'':'-'+stem)+'.wav';
    files.push({stem,filename,sha256:await sha(wav),measurements:measurements(buffer)});download(wav,filename,'audio/wav');
   }
   const report={version:bundle.sound_design?'performance-export-3':'performance-export-2',sound_design:bundle.sound_design,sound_design_bytes:bundle.sound_design_bytes,sound_design_sha256:bundle.sound_design_sha256,sound_design_event_bytes:bundle.sound_design_event_bytes,final_fade_s:bundle.sound_design?.final_fade_s,stem_layout:stemsFor(performed),status:isDraft?'DRAFT_NOT_APPROVED':'APPROVED_PERFORMANCE',bundle_id:bundle.id,scene_hash:bundle.scene_hash,composition_hash:bundle.composition_hash,video_sha256:bundle.video_sha256,plan_bytes:isDraft?stable(plan)+'\n':approved!.payload,approval:isDraft?null:approved!.approval,controls:e.timeline.history.slice(e.historyStart),control_traces:controlTraces.current.map(envelope=>({envelope,intervals:latencyIntervals(envelope)})),events:performed,event_bytes:stable(performed)+'\n',event_hash:await hash(performed),mode,mix_automation:mix,files,duration_s:bundle.scene.duration_s,tails:'clamped at scene end; no stretched audio',video_timestamp_offset_s:0,clock:{sample_rate:e.context?.sampleRate,base_latency:e.context?.baseLatency,output_latency:e.context?.outputLatency??null,drift_samples_s:drifts,physical_output_measured:false},audition_status:'AUDITION_PENDING',selection:bundle.selection,playback_window:bundle.playback_window,playback_window_bytes:bundle.playback_window_bytes,playback_window_sha256:bundle.playback_window_sha256,source_events_bytes:bundle.source_events_bytes,scene_input_bytes:bundle.scene_input_bytes,role_supplement:bundle.role_supplement,playback_policy:bundle.playback_policy,music_handoff_binding:bundle.music_handoff_binding,frame_timing:frameTiming.current,label:bundle.label};
   const completeReport={...report,effect_mix:{...EFFECT_MIX,reference:"original dry soundtrack RMS; overlapping effects measured together"},piano_mix:bundle.piano_mix,piano_mix_bytes:bundle.piano_mix_bytes,piano_mix_sha256:bundle.piano_mix_sha256,piano_event_bytes:bundle.piano_event_bytes};
   download(JSON.stringify(completeReport,null,2),prefix+'.json');(window as any).__lastExport=completeReport;setMessage(isDraft?`Draft mix + ${files.length-1} stems exported · no approval claimed`:`Played mix + ${files.length-1} stems + score/control log exported`);
  }catch(error){setError(String(error));}finally{setBusy(false);}
 }
 useEffect(()=>{(window as any).__studio={snapshot:()=>({mode,complete:engine.current?.completed,time:engine.current?.now(),playing:engine.current?.timeline.playing,generation:engine.current?.timeline.generation,history:engine.current?.timeline.history,scheduled:engine.current?.metrics,approval:approved,draft_conducting:draftConducting,tonic:engine.current?.timeline.currentTonic(),chord:engine.current?.timeline.currentChord(),bundle_id:bundle?.id,sample_rate:engine.current?.context?.sampleRate,preparation:{ready:engine.current?.timeline.preparationReady,error:engine.current?.timeline.preparationError,cache_buffers:engine.current?.cache.size,cache_bytes:engine.current?[...engine.current.cache.values()].reduce((n,b)=>n+b.length*4,0):0,refresh:engine.current?.refreshStats},traces:controlTraces.current.map(envelope=>({envelope,intervals:latencyIntervals(envelope)})),drifts,frame_timing:frameTiming.current}),performed:()=>({events:engine.current?.timeline.performedEvents(),controls:engine.current?.timeline.history.slice(engine.current.historyStart),traces:controlTraces.current.map(envelope=>({envelope,intervals:latencyIntervals(envelope)})),approval:approved,bundle_id:bundle?.id}),offline:async()=>{if(!engine.current)throw Error('Play a fixture first');const b=await renderPerformedOffline(engine.current.timeline,bundle!.scene.duration_s,gain,{soundtrack,foley});return measurements(b);}};});
 const activeEvents=(engine.current?.timeline.events??bundle?.events??[]).filter(e=>e.resolved_time_s<duration&&e.resolved_time_s+e.duration_s>0),history=engine.current?.timeline.history??[];
 const sourceChord=bundle?.composition.harmony.find(c=>c.start_tick/bundle.composition.ppq*60/bundle.composition.tempo_map[0].bpm<=time&&(c.start_tick+c.duration_ticks)/bundle.composition.ppq*60/bundle.composition.tempo_map[0].bpm>time);
 const activeChord=engine.current?.timeline.currentChord(time)??sourceChord;
 const manualAvailable=!!engine.current&&manualChoices(engine.current.timeline,time).length>0;
 const pendingChange=engine.current?.timeline.pending[0];
 const latestChange=[...history].reverse().find(d=>d.status==='executed');
 const keyChangeHint=pendingChange?`Key change ${pendingChange.status==='transitioning'?'in progress':'queued'} · tonic at ${pendingChange.arrival_scene_s?.toFixed(2)}s`:!playing?'Play the soundtrack to try a manual key change.':!manualAvailable?'No prepared transition fits before the ending. Return to the start to try again.':latestChange?`Key changed · ${keys[engine.current!.timeline.currentTonic()]} · manual input is ready again.`:'Manual input · a prepared chord transition leads into the new key.';
 const activeFeatures=bundle?.control_track?.events.filter(e=>e.start_s<=time&&time<e.end_s)??[];
 return <main className="viewer"><header><div><span className="eyebrow">ANIMATION & SOUND</span><h1>SceneScore<span className="dot">.</span></h1></div><div className="source"><strong>LAST INPUT · {mode}</strong><span>{approved?'MANUAL_PLAN · '+(mode==='SYNTHETIC_TEST'?'TEST APPROVAL':'APPROVED'):'DRAFT · AUDITION PENDING'}</span></div></header>
 {onBack?<button className="back-library" onClick={onBack}>← Video library</button>:<a className="back-library" href="/">← Video library</a>}
 <div className="workspace"><section className="stage"><div className="section-line"><h2>{bundle?.title??'Loading animation…'}</h2><span className="sound-status">Live browser audio</span></div>
 <div className="screen"><video ref={video} src={videoURL||undefined} muted playsInline preload="auto" onLoadedMetadata={e=>{if(!bundle)return;const length=e.currentTarget.duration;if(!Number.isFinite(length)||Math.abs(length-bundle.scene.duration_s)>Math.max(.15,2*bundle.scene.fps_base/bundle.scene.fps)){setError('Video duration does not match its scene sidecar.');setMediaReady(false);pause();}else setMediaReady(true);}} onWaiting={()=>{setTimeout(()=>{if(engine.current?.timeline.playing&&video.current&&video.current.readyState<2&&!video.current.seeking){pause();setMessage('Video buffering · transport paused');}},200);}} onError={()=>{setMediaReady(false);pause();setError('Video playback failed. Reload the matched scene.');}} /><div className="screen-caption"><span>{bundle?.animation_label??bundle?.source??'Loading scene'}</span><span>{time.toFixed(2)} / {bundle?.scene.duration_s??0}s</span></div></div>
 <div className="transport"><button className="primary primary-play" disabled={busy||!bundle||!mediaReady} onClick={()=>playing?pause():void start(!approved)}>{playing?'Pause':time>0&&time<duration?'Resume':'▶ Watch & listen'}</button><button disabled={busy||!mediaReady} onClick={()=>{engine.current?.seek(0);video.current?.pause();if(video.current)video.current.currentTime=0;replayFired.current=false;setMessage('Returned to start');}}>↤ Start</button><span className="key">{keys[engine.current?(engine.current.timeline.currentTonic()):(bundle?.composition.key_map[0].tonic_pc??0)]} <small>{activeChord?keys[activeChord.root_pc]+' '+activeChord.quality:'blues centre'}</small></span><label className="volume">Volume <input aria-label="Master volume" type="range" min="-36" max="0" value={gain} onChange={e=>{setGain(+e.target.value);engine.current?.setGain(+e.target.value);}}/>{gain} dB</label><button aria-pressed={mute} onClick={()=>{setMute(!mute);engine.current?.setMute(!mute);}}>{mute?'Unmute':'Mute'}</button></div>
 {!headsetDetected&&<div className="manual-key-change"><button className="primary" disabled={busy||!mediaReady||!playing||!manualAvailable} onClick={changeKey}>Change key</button><span role="status">{keyChangeHint}</span></div>}
 <label className="seek">Position<input aria-label="Seek position" type="range" min="0" max={bundle?.scene.duration_s??0} step=".1" value={time} onChange={e=>{engine.current?.seek(+e.target.value);if(video.current){video.current.pause();video.current.currentTime=+e.target.value;}}}/></label>
 <div className="timeline">{(['soundtrack','foley','controls'] as const).map((lane,i)=><div className="lane" key={lane}><div className="lane-label"><span>0{i+1}</span><b>{lane==='soundtrack'?'Soundtrack':lane==='foley'?'Collision / Foley':'Conducting'}</b>{lane!=='controls'&&<input aria-label={`Enable ${lane}`} type="checkbox" checked={lane==='soundtrack'?soundtrack:foley} onChange={e=>{if(lane==='soundtrack')setSoundtrack(e.target.checked);else setFoley(e.target.checked);engine.current?.setLanes({soundtrack:lane==='soundtrack'?e.target.checked:soundtrack,foley:lane==='foley'?e.target.checked:foley});}}/>}</div><div className="lane-events">{lane==='controls'?history.map((d,i)=><i key={i} className={'control-mark '+d.status} style={{left:Math.min(99,(d.boundary_s??d.requested_scene_s)/duration*100)+'%'}} title={d.reason??d.status}/>):activeEvents.filter(e=>lane==='foley'?e.event_type==='foley':e.event_type!=='foley').map(e=><i key={e.id} style={{left:e.resolved_time_s/duration*100+'%',width:Math.max(.3,Math.min(e.duration_s,duration-e.resolved_time_s)/duration*100)+'%',top:lane==='soundtrack'?(e.midi_pitch===null?34:6+(e.midi_pitch%12)*2)+'px':'15px',opacity:e.event_type==='brush'?.3:.65}}/>)}<div className="playhead" style={{left:time/duration*100+'%'}}/></div></div>)}</div>
 {bundle?.control_track&&<p className="hint">Motion: {activeFeatures.length?activeFeatures.map(e=>e.feature.replaceAll('_',' ')+(e.driver===null?' · unknown':e.driver<.33?' · low':e.driver<.67?' · medium':' · high')).join(' / '):'source phrase'} · articulation follows the mapped score.</p>}
 {bundle?.label&&<p className="hint">{bundle.label}</p>}
 <div role="status" className="status">{message}</div>{error&&<p role="alert" className="error">{error}</p>}
 </section><aside><span className="eyebrow">SOUNDTRACK</span><h2>{bundle?.composition.title??'Original score'}</h2><p className="muted">{bundle?.composition.tempo_map[0].bpm??96} BPM · {bundle?.composition.meter.join('/')??'4/4'}</p><label className="viewer-track">Soundtrack version<select aria-label="Soundtrack version" value={selection} disabled={busy} onChange={e=>setSelection(e.target.value)}>{catalog.map(entry=><option key={entry.id} value={entry.id}>{soundtrackName(entry)}</option>)}</select></label><p className="watch-note">Music is performed live in your browser. Scene effects follow the animation.</p><div className="sound-switches"><label><input type="checkbox" aria-label="Music" checked={soundtrack} onChange={e=>{setSoundtrack(e.target.checked);engine.current?.setLanes({soundtrack:e.target.checked,foley});}}/>Music</label><label><input type="checkbox" aria-label="Sound effects" checked={foley} onChange={e=>{setFoley(e.target.checked);engine.current?.setLanes({soundtrack,foley:e.target.checked});}}/>Sound effects</label></div><button className="export" disabled={busy||!bundle} onClick={()=>void exportAudio(true)}>Download draft audio + stems</button>
 <button className="export" disabled={busy||!bundle||!mediaReady} onClick={downloadSource}>Download video + sidecar</button>
 <details className="advanced-tools"><summary>Arrangement & conducting</summary><button disabled={busy||!bundle||!mediaReady} onClick={()=>void startDemo()}>{bundle?.music_vertical?'Start music demo':'Start blink demo'}</button><p className="hint">Optional conducting demo · draft approval remains pending.</p>
 <label>Conducting focus<select aria-label="Conducting focus" value={plan?.motion_policy.focus_object_id??''} disabled={playing||musicStudio} onChange={e=>{if(plan)edited({...plan,motion_policy:{...plan.motion_policy,focus_object_id:e.target.value}});}}>{bundle?.scene.objects.filter(o=>!(bundle.role_supplement as RoleSupplement|null)?.scored_object_ids||(bundle.role_supplement as RoleSupplement).scored_object_ids.includes(o.object_id)).map(o=><option key={o.object_id} value={o.object_id}>{o.object_id.split(':').at(-1)}</option>)}</select></label><p className="hint">World Z · up +2 / down −2. Stationary motion holds the key.</p>
 <div className="register"><label>Low note<input aria-label="Low note" type="number" min="28" max="60" value={plan?.register_min??28} disabled={playing||musicStudio} onChange={e=>{if(plan&&+e.target.value>=28&&+e.target.value<=plan.register_max-24)edited({...plan,register_min:+e.target.value});}}/></label><label>High note<input aria-label="High note" type="number" min="60" max="96" value={plan?.register_max??96} disabled={playing||musicStudio} onChange={e=>{if(plan&&+e.target.value<=96&&+e.target.value>=plan.register_min+24)edited({...plan,register_max:+e.target.value});}}/></label></div>
 <details><summary>Mapping rules & exact plan</summary><dl>{plan?.mappings.map(m=><React.Fragment key={m.feature}><dt>{m.feature.replace('_',' ')}</dt><dd>{m.lane} · {m.output_min}…{m.output_max}</dd></React.Fragment>)}</dl><button onClick={()=>plan&&download(stable(plan)+'\n','arrangement-plan.json')}>Export editable plan</button></details>
 <div className="approval"><label>Reviewer<input aria-label="Reviewer" placeholder="Your name" value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><button disabled={!plan||busy||!reviewer.trim()} onClick={()=>void accept()}>Approve exact plan</button><button disabled={!approved} onClick={()=>{pause();setApproved(null);setArmed(false);setMessage('Plan rejected · audition remains available');}}>Reject / clear</button><p className="hint">Approval records the plan and input hashes. Listening judgments remain separate.</p></div>
 <div className="conduct"><p className="hint">Recent control: {mode}. Choose the current source in the Muse panel below.</p><label className="arm"><input type="checkbox" checked={armed} disabled={!approved&&!draftConducting} onChange={e=>setArmed(e.target.checked)}/> Arm conducting</label><button className="primary" disabled={!playing||!armed||(!approved&&!draftConducting)} onClick={conduct}>Request modulation <kbd>M</kbd></button><p className="hint">Double only. Gain and articulation stay fixed. Triple and amplitude controls are disabled.</p></div>
 <button className="export" disabled={busy||!approved||!engine.current} onClick={()=>void exportAudio(false)}>Export approved performance ↗</button></details></aside></div>
 <details className="advanced-tools"><summary>Muse & input controls</summary><MusePanel onHeadsetDetected={setHeadsetDetected} onEnvelope={receiveControl} onKeyboardRequest={conduct} getMusicContext={getMusicContext} createSimulation={createSimulation} createFromGesture={createFromGesture} transportStatus={playing?(draftConducting?'Draft conducting · unapproved':!approved?'Draft audition · unapproved':'Approved playback'):'Music paused'} /></details>
 <details className="diagnostics"><summary>Timing & provenance</summary><p>Audio context: {engine.current?.context?.sampleRate??'locked'} Hz · transport generation {engine.current?.timeline.generation??0} · video drift {drifts.length?(drifts.at(-1)!*1000).toFixed(1):'—'} ms (software timestamps)</p><p>Acoustic / display onset not measured. Muse connection and quality are shown above. No external model is required for playback.</p><pre>{JSON.stringify({scene:bundle?.scene_hash,plan:approved?.approval.approved_payload_sha256,active_motion:activeFeatures,actions:history},null,2)}</pre></details><footer>LOCAL-FIRST · EDITABLE SCORE · NO CLOUD IN PLAYBACK <span>Audition before performance.</span></footer></main>;
}
import {direction as directionAt} from '../../../packages/audio/model';
createRoot(document.getElementById('root')!).render(musicStudio||reviewStudio?<App/>:<Library renderPlayer={(entries,record,back)=><App initialEntries={entries} imported={record} onBack={back}/>}/>);
