import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Approval,ArrangementPlan} from '../../../packages/contracts/generated';
import {approve,Bundle,copy,hash,keyboardAction,Mode,sha,stable,verifyApproval,verifyBundle,bound} from '../../../packages/audio/model';
import {Engine,measurements,pcmWav,renderOffline} from '../../../packages/audio/engine';
import {Timeline,videoCorrection} from '../../../packages/audio/transport';
import {stemFor} from '../../../packages/audio/mix';
import './style.css';
type Entry={id:string;title:string;variant:string;groove:string;url:string;sha256:string};
const keys=['C','D♭','D','E♭','E','F','G♭','G','A♭','A','B♭','B'];
function download(value:BlobPart,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function App(){
 const [catalog,setCatalog]=useState<Entry[]>([]),[selection,setSelection]=useState('contact-brush_swing_light_v1'),[bundle,setBundle]=useState<Bundle|null>(null),[plan,setPlan]=useState<ArrangementPlan|null>(null),[videoURL,setVideoURL]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('Loading local scene…'),[busy,setBusy]=useState(false),[mode,setMode]=useState<Mode>('KEYBOARD'),[reviewer,setReviewer]=useState(''),[approved,setApproved]=useState<{payload:string;approval:Approval}|null>(null),[tick,setTick]=useState(0),[gain,setGain]=useState(-18),[mute,setMute]=useState(false),[soundtrack,setSoundtrack]=useState(true),[foley,setFoley]=useState(true),[armed,setArmed]=useState(false),[drifts,setDrifts]=useState<number[]>([]);
 const engine=useRef<Engine|null>(null),video=useRef<HTMLVideoElement>(null),videoObject=useRef(''),loadGeneration=useRef(0),lastCorrection=useRef(-10),replayFired=useRef(false);
 const time=engine.current?.now()??0,playing=engine.current?.timeline.playing??false;
 useEffect(()=>{fetch('/studio/catalog.json').then(r=>{if(!r.ok)throw Error('Run the local scene preparation command before opening the studio.');return r.json();}).then(d=>setCatalog(d.entries)).catch(e=>setError(String(e)));return()=>{void engine.current?.close();if(videoObject.current)URL.revokeObjectURL(videoObject.current);};},[]);
 useEffect(()=>{if(!catalog.length)return;void load(selection);},[catalog,selection]);
 async function load(id:string){const generation=++loadGeneration.current;setBusy(true);setError('');setMessage('Checking scene and video hashes…');setApproved(null);setArmed(false);await engine.current?.close();engine.current=null;try{const entry=catalog.find(e=>e.id===id);if(!entry)throw Error('Unknown local scene');const response=await fetch('/studio/'+entry.url);if(!response.ok)throw Error('Scene could not be loaded');const raw=await response.arrayBuffer();if(await sha(raw)!==entry.sha256)throw Error('Scene bundle hash mismatch');const b=JSON.parse(new TextDecoder().decode(raw)) as Bundle;const responseVideo=await fetch('/studio/'+b.video);if(!responseVideo.ok)throw Error('Matched video is unavailable');const media=await responseVideo.arrayBuffer();const p=await verifyBundle(b,media);if(generation!==loadGeneration.current)return;if(videoObject.current)URL.revokeObjectURL(videoObject.current);videoObject.current=URL.createObjectURL(new Blob([media],{type:'video/mp4'}));setVideoURL(videoObject.current);setBundle(b);setPlan(p);setDrifts([]);setMessage('Matched scene verified · ready to audition');replayFired.current=false;}catch(e){setError(String(e));setBundle(null);setPlan(null);}finally{if(generation===loadGeneration.current)setBusy(false);}}
 function edited(next:ArrangementPlan){if(playing){setError('Pause before editing the arrangement.');return;}setPlan(next);setApproved(null);setArmed(false);void engine.current?.close();engine.current=null;setMessage('Arrangement changed · approval cleared');setTick(n=>n+1);}
 async function newEngine(preview:boolean){if(!bundle||!plan)throw Error('Load a scene first');if(!preview&&!approved)throw Error('Approve this exact arrangement before performance');const verified=preview?plan:await verifyApproval(approved!.payload,approved!.approval,bundle);const b=copy(bundle);b.events=b.events.map(e=>({...e,midi_pitch:e.midi_pitch===null?null:bound(e.midi_pitch,verified.register_min,verified.register_max)}));const timeline=new Timeline(b,verified,approved?.approval.approved_payload_sha256??await hash(verified));if(engine.current)await engine.current.close();const next=new Engine(timeline);next.gainDb=gain;next.mute=mute;next.lanes={soundtrack,foley};next.onTick=()=>setTick(n=>n+1);next.onSuspend=()=>{video.current?.pause();setMessage('Audio suspended · press Play to resume');};engine.current=next;return next;}
 async function start(preview=false){setError('');try{let e=engine.current;if(!e)e=await newEngine(preview);if(!preview)await verifyApproval(approved!.payload,approved!.approval,bundle!);await e.unlock();if(video.current){if(Math.abs(video.current.currentTime-e.timeline.position)>.03)video.current.currentTime=e.timeline.position;await video.current.play();}await e.play();setMessage(preview?'AUDITION PREVIEW · unapproved':mode==='SYNTHETIC_TEST'?'SYNTHETIC TEST · test approval only':'Approved plan playing locally');}catch(e){engine.current?.pause();video.current?.pause();setError(String(e));}}
 function pause(){engine.current?.pause();video.current?.pause();setMessage('Paused · pending controls cleared');}
 async function accept(){if(!plan)return;try{pause();const a=await approve(plan,reviewer,mode==='SYNTHETIC_TEST');setApproved(a);await engine.current?.close();engine.current=null;setMessage(mode==='SYNTHETIC_TEST'?'Test approval recorded · no human audition claimed':'Exact plan approved · listening status still pending');}catch(e){setError(String(e));}}
 function conduct(){const e=engine.current;if(!e||!approved||!armed||!e.timeline.playing){setMessage('Approve, play and arm conducting first');return;}try{const at=e.now();const p=e.timeline.plan;const sign=directionAt(bundle!,p,at);const action=keyboardAction(p,approved.approval.approved_payload_sha256,e.timeline.epoch,e.context!.currentTime,sign,mode,gain);const result=e.submit(action);setMessage(result.status==='queued'?`${sign>0?'+':'−'}2 semitones queued at ${result.boundary_s!.toFixed(2)}s`:result.reason??result.status);}catch(error){setError(String(error));}}
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if((event.target as HTMLElement).matches('input,select,textarea'))return;if(event.code==='Space'){event.preventDefault();playing?pause():void start();}if(event.code==='KeyM'){event.preventDefault();conduct();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);});
 useEffect(()=>{if(mode==='SYNTHETIC_TEST'&&playing&&armed&&time>=18&&!replayFired.current){replayFired.current=true;conduct();}},[tick,mode,armed]);
 useEffect(()=>{const v=video.current;if(!v)return;let cancelled=false,handle=0;const callback=(_now:number,meta?:{mediaTime:number})=>{if(cancelled)return;const e=engine.current;if(e?.timeline.playing){const drift=(meta?.mediaTime??v.currentTime)-e.now();setDrifts(prev=>[...prev.slice(-199),drift]);const correction=videoCorrection(drift,e.now()-lastCorrection.current);if(correction.seek){v.currentTime=e.now();lastCorrection.current=e.now();}else v.playbackRate=correction.rate;}if('requestVideoFrameCallback'in v)handle=v.requestVideoFrameCallback(callback);else handle=requestAnimationFrame(callback);};if('requestVideoFrameCallback'in v)handle=v.requestVideoFrameCallback(callback);else handle=requestAnimationFrame(callback);return()=>{cancelled=true;if('cancelVideoFrameCallback'in v)v.cancelVideoFrameCallback(handle);else cancelAnimationFrame(handle);};},[videoURL]);
 async function exportAudio(isDraft:boolean){
  if(!bundle||!plan)return;setError('');setBusy(true);
  try{
   const e=engine.current??await newEngine(true);
   if(!isDraft){if(!approved)throw Error('An approved performance is required');await verifyApproval(approved.payload,approved.approval,bundle);e.exportReady();}
   pause();const mix=isDraft?[{scene_s:0,gain_db:gain,muted:mute,lanes:{soundtrack,foley}}]:e.exportMix();
   const prefix=isDraft?'scenescore-DRAFT':'scenescore-performance';
   const files=[];
   for(const stem of ['mix','piano','bass','brush','foley']){
    const events=stem==='mix'?e.timeline.events:e.timeline.events.filter(event=>stemFor(event)===stem);
    const buffer=await renderOffline(events,bundle.scene.duration_s,gain,{soundtrack,foley},48000,mix),wav=pcmWav(buffer),filename=prefix+(stem==='mix'?'':'-'+stem)+'.wav';
    files.push({stem,filename,sha256:await sha(wav),measurements:measurements(buffer)});download(wav,filename,'audio/wav');
   }
   const report={version:'performance-export-2',status:isDraft?'DRAFT_NOT_APPROVED':'APPROVED_PERFORMANCE',bundle_id:bundle.id,scene_hash:bundle.scene_hash,composition_hash:bundle.composition_hash,video_sha256:bundle.video_sha256,plan_bytes:isDraft?stable(plan)+'\n':approved!.payload,approval:isDraft?null:approved!.approval,controls:isDraft?[]:e.timeline.history.slice(e.historyStart),events:e.timeline.events,event_bytes:stable(e.timeline.events)+'\n',event_hash:await hash(e.timeline.events),mode,mix_automation:mix,files,duration_s:bundle.scene.duration_s,tails:'clamped at scene end; no stretched audio',video_timestamp_offset_s:0,clock:{sample_rate:e.context?.sampleRate,base_latency:e.context?.baseLatency,output_latency:e.context?.outputLatency??null,drift_samples_s:drifts,physical_output_measured:false},audition_status:'AUDITION_PENDING'};
   download(JSON.stringify(report,null,2),prefix+'.json');(window as any).__lastExport=report;setMessage(isDraft?'Draft mix + four stems exported · no approval claimed':'Played mix + four stems + score/control log exported');
  }catch(error){setError(String(error));}finally{setBusy(false);}
 }
 useEffect(()=>{(window as any).__studio={snapshot:()=>({mode,complete:engine.current?.completed,time:engine.current?.now(),playing:engine.current?.timeline.playing,generation:engine.current?.timeline.generation,history:engine.current?.timeline.history,scheduled:engine.current?.metrics,approval:approved,drifts}),offline:async()=>{if(!engine.current)throw Error('Play a fixture first');const b=await renderOffline(engine.current.timeline.events,bundle!.scene.duration_s,gain,{soundtrack,foley});return measurements(b);}};});
 const activeEvents=engine.current?.timeline.events??bundle?.events??[],history=engine.current?.timeline.history??[];
 const activeChord=bundle?.composition.harmony.find(c=>c.start_tick/bundle.composition.ppq*60/bundle.composition.tempo_map[0].bpm<=time&&(c.start_tick+c.duration_ticks)/bundle.composition.ppq*60/bundle.composition.tempo_map[0].bpm>time);
 return <main><header><div><span className="eyebrow">LOCAL ANIMATION · ORIGINAL MUSIC</span><h1>SceneScore<span className="dot">.</span></h1></div><div className="source"><strong>{mode}</strong><span>{approved?'MANUAL_PLAN · '+(mode==='SYNTHETIC_TEST'?'TEST APPROVAL':'APPROVED'):'BASELINE · AUDITION PENDING'}</span></div></header>
 <div className="workspace"><section className="stage"><div className="section-line"><h2>{bundle?.title??'Scene preview'}</h2><label>Trajectory<select aria-label="Trajectory" value={selection.startsWith('near-miss')?'near-miss':'contact'} disabled={busy||playing} onChange={e=>setSelection(e.target.value+'-'+(catalog.find(c=>c.id===selection)?.groove??'brush_swing_light_v1'))}><option value="contact">Contact</option><option value="near-miss">Near miss</option></select></label></div>
 <div className="screen"><video ref={video} src={videoURL||undefined} muted playsInline preload="auto" onWaiting={()=>{setTimeout(()=>{if(engine.current?.timeline.playing&&video.current&&video.current.readyState<2&&!video.current.seeking){pause();setMessage('Video buffering · transport paused');}},200);}} onError={()=>setError('Video playback failed. Reload the matched scene.')} /><div className="screen-caption"><span>EVALUATED BLENDER SCENE</span><span>{time.toFixed(2)} / {bundle?.scene.duration_s??30}s</span></div></div>
 <div className="transport"><button className="primary" disabled={busy||(!approved&&!playing)} onClick={()=>playing?pause():void start()}>{playing?'Pause':'Play approved'}</button><button disabled={busy||!bundle} onClick={()=>void start(true)}>Audition draft</button><button onClick={()=>{engine.current?.seek(0);if(video.current)video.current.currentTime=0;replayFired.current=false;setMessage('Returned to start · new transport generation');}}>↤ Start</button><span className="key">{keys[engine.current?(engine.current.timeline.pending.length?engine.current.timeline.previousTonic:engine.current.timeline.tonic):(bundle?.composition.key_map[0].tonic_pc??0)]} <small>{activeChord?.quality??'blues centre'}</small></span><label className="volume">Volume <input aria-label="Master volume" type="range" min="-36" max="0" value={gain} onChange={e=>{setGain(+e.target.value);engine.current?.setGain(+e.target.value);}}/>{gain} dB</label><button aria-pressed={mute} onClick={()=>{setMute(!mute);engine.current?.setMute(!mute);}}>{mute?'Unmute':'Mute'}</button></div>
 <label className="seek">Position<input aria-label="Seek position" type="range" min="0" max={bundle?.scene.duration_s??30} step=".1" value={time} onChange={e=>{engine.current?.seek(+e.target.value);if(video.current){video.current.pause();video.current.currentTime=+e.target.value;}}}/></label>
 <div className="timeline">{(['soundtrack','foley','controls'] as const).map((lane,i)=><div className="lane" key={lane}><div className="lane-label"><span>0{i+1}</span><b>{lane==='soundtrack'?'Soundtrack':lane==='foley'?'Collision / Foley':'Conducting'}</b>{lane!=='controls'&&<input aria-label={`Enable ${lane}`} type="checkbox" checked={lane==='soundtrack'?soundtrack:foley} onChange={e=>{if(lane==='soundtrack')setSoundtrack(e.target.checked);else setFoley(e.target.checked);engine.current?.setLanes({soundtrack:lane==='soundtrack'?e.target.checked:soundtrack,foley:lane==='foley'?e.target.checked:foley});}}/>}</div><div className="lane-events">{lane==='controls'?history.map((d,i)=><i key={i} className={'control-mark '+d.status} style={{left:Math.min(99,(d.boundary_s??d.requested_scene_s)/30*100)+'%'}} title={d.reason??d.status}/>):activeEvents.filter(e=>lane==='foley'?e.event_type==='foley':e.event_type!=='foley').map(e=><i key={e.id} style={{left:e.resolved_time_s/30*100+'%',width:Math.max(.3,e.duration_s/30*100)+'%',top:lane==='soundtrack'?(e.midi_pitch===null?34:6+(e.midi_pitch%12)*2)+'px':'15px',opacity:e.event_type==='brush'?.3:.65}}/>)}<div className="playhead" style={{left:time/30*100+'%'}}/></div></div>)}</div>
 <div role="status" className="status">{message}</div>{error&&<p role="alert" className="error">{error}</p>}
 </section><aside><span className="eyebrow">ARRANGEMENT</span><h2>Tilted Blue</h2><p className="muted">Original blues swing · 96 BPM · 4/4</p><label>Brush groove<select aria-label="Brush groove" value={catalog.find(c=>c.id===selection)?.groove??'brush_swing_light_v1'} disabled={playing||busy} onChange={e=>setSelection((bundle?.variant??'contact')+'-'+e.target.value)}><option value="brush_swing_light_v1">Light swing</option><option value="brush_ballad_sparse_v1">Sparse brush</option><option value="brush_straight_rag_v1">Straight rag</option></select></label>
 <label>Conducting focus<select aria-label="Conducting focus" value={plan?.motion_policy.focus_object_id??''} disabled={playing} onChange={e=>{if(plan)edited({...plan,motion_policy:{...plan.motion_policy,focus_object_id:e.target.value}});}}>{bundle?.scene.objects.map(o=><option key={o.object_id} value={o.object_id}>{o.object_id.split(':').at(-1)}</option>)}</select></label><p className="hint">World Z · up +2 / down −2. Stationary motion holds the key.</p>
 <div className="register"><label>Low note<input aria-label="Low note" type="number" min="28" max="60" value={plan?.register_min??28} disabled={playing} onChange={e=>{if(plan&&+e.target.value>=28&&+e.target.value<=plan.register_max-24)edited({...plan,register_min:+e.target.value});}}/></label><label>High note<input aria-label="High note" type="number" min="60" max="96" value={plan?.register_max??96} disabled={playing} onChange={e=>{if(plan&&+e.target.value<=96&&+e.target.value>=plan.register_min+24)edited({...plan,register_max:+e.target.value});}}/></label></div>
 <details><summary>Mapping rules & exact plan</summary><dl>{plan?.mappings.map(m=><React.Fragment key={m.feature}><dt>{m.feature.replace('_',' ')}</dt><dd>{m.lane} · {m.output_min}…{m.output_max}</dd></React.Fragment>)}</dl><button onClick={()=>plan&&download(stable(plan)+'\n','arrangement-plan.json')}>Export editable plan</button></details>
 <div className="approval"><label>Reviewer<input aria-label="Reviewer" placeholder="Your name" value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><button disabled={!plan||busy||!reviewer.trim()} onClick={()=>void accept()}>Approve exact plan</button><button disabled={!approved} onClick={()=>{pause();setApproved(null);setArmed(false);setMessage('Plan rejected · audition remains available');}}>Reject / clear</button><p className="hint">Approval records the plan and input hashes. Listening judgments remain separate.</p></div>
 <div className="conduct"><label>Input source<select aria-label="Input source" value={mode} disabled={playing} onChange={e=>{pause();setMode(e.target.value as Mode);setArmed(false);setApproved(null);replayFired.current=false;}}><option value="KEYBOARD">Keyboard</option><option value="SYNTHETIC_TEST">Synthetic replay · 18s</option><option disabled value="REAL_REPLAY">Real replay · unavailable</option><option disabled value="LIVE_MUSE">Live Muse · unverified</option></select></label><label className="arm"><input type="checkbox" checked={armed} disabled={!approved} onChange={e=>setArmed(e.target.checked)}/> Arm conducting</label><button className="primary" disabled={!playing||!armed||!approved} onClick={conduct}>Request modulation <kbd>M</kbd></button><p className="hint">Double only. Gain and articulation stay fixed. Triple and amplitude controls are disabled.</p></div>
 <button className="export" disabled={busy||!bundle} onClick={()=>void exportAudio(true)}>Export draft audition</button><button className="export" disabled={busy||!approved||!engine.current} onClick={()=>void exportAudio(false)}>Export audio + score log ↗</button></aside></div>
 <details className="diagnostics"><summary>Timing & provenance</summary><p>Audio context: {engine.current?.context?.sampleRate??'locked'} Hz · transport generation {engine.current?.timeline.generation??0} · video drift {drifts.length?(drifts.at(-1)!*1000).toFixed(1):'—'} ms (software timestamps)</p><p>Acoustic / display onset not measured. Muse not connected. No external model is required for playback.</p><pre>{JSON.stringify({scene:bundle?.scene_hash,plan:approved?.approval.approved_payload_sha256,actions:history},null,2)}</pre></details><footer>LOCAL-FIRST · EDITABLE SCORE · NO CLOUD IN PLAYBACK <span>Audition before performance.</span></footer></main>;
}
import {direction as directionAt} from '../../../packages/audio/model';
createRoot(document.getElementById('root')!).render(<App/>);
